# Deploy documentation to GitHub Pages
name: Deploy Pages

on:
  push:
    branches:
      - main  # Trigger the workflow only on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering

# Add permissions block
permissions:
  contents: write  # Required for pushing to gh-pages branch
  pages: write     # Required for deploying GitHub pages
  id-token: write  # Required for authentication

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install griffe>=0.37
          pip install mkdocs-material==9.5.1
          pip install mkdocstrings>=0.20
          pip install mkdocstrings-python>=1.7.0
          pip install mkdocs-autorefs>=0.3.1
          pip install pymdown-extensions>=6.3
          pip install mkdocs>=1.4.0

      - name: Build documentation
        run: mkdocs build --clean --verbose

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: site
          token: ${{ secrets.GH_PAT }}
          git-config-name: ${{ github.actor }}
          git-config-email: ${{ github.event.head_commit.author.email }}
          commit-message: "docs: update documentation"
          single-commit: false
