name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: |
          **/requirements*.txt
          pyproject.toml

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        
    - name: Configure Poetry
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
        
    - name: Verify version matches release
      run: |
        # Get release tag version (strip the 'v' prefix)
        RELEASE_VERSION=${GITHUB_REF#refs/tags/v}
        
        # Update version in pyproject.toml to match release
        poetry version $RELEASE_VERSION
        
        echo "Building version: $RELEASE_VERSION"
        
    - name: Build and publish
      run: |
        poetry build
        poetry publish --no-interaction 